### PR TITLE
Update rq parameter name to is_async for python 3.7

### LINKED ISSUE #44: Async is now a reserved word in python 3.7
Python 3.7 makes `async` a reserved word: https://docs.python.org/3/reference/compound_stmts.html#async

This causes errors where used with [rq](https://github.com/rq/rq) as a parameter name: 
https://github.com/chaoss/grimoirelab-kingarthur/blob/master/arthur/scheduler.py#L90
https://github.com/chaoss/grimoirelab-kingarthur/blob/master/tests/test_jobs.py#L544

Rq version 0.12 changes the parameter name to `is_async`: [CHANGES.md](https://github.com/rq/rq/blob/6a376191d92bc663be71390db7405820761a0ecb/CHANGES.md)

On travis-ci using

    dist: xenial
    python:
      - "3.7"

will show the error: [build](https://travis-ci.org/cewilliams/grimoirelab-kingarthur/builds/516612386)

### PR DESCRIPTION
**Pull request by cewilliams**
Fixes #44

### CODE REVIEW

**Comment by valeriocos** [comment]
Thank you @cewilliams for the PR and your interest in KingArthur. Indeed the issue you report is interesting, but I'm not totally sure about the change you propose since all Grimoirelab components rely on python 3.4, however for some components, (e.g., [perceval](https://github.com/chaoss/grimoirelab-perceval/blob/master/.travis.yml)) the tests on travis are executed for python 3.4., 3.5 and 3.6. 

What do you think @sduenas ?

**Comment by cewilliams** [comment]
@valeriocos - I can understand not worrying about the newer versions of python. The parameter change in rq >= 0.12 should already be throwing deprecation warnings, however, which this would fix. Also would future-proof the code against when rq removes the deprecated parameter.

Would you be more certain about this change without the travis change?

**Comment by valeriocos** [comment]
In the [setup.py](https://github.com/chaoss/grimoirelab-kingarthur/blob/master/setup.py#L99) and [requirements.txt](https://github.com/chaoss/grimoirelab-kingarthur/blob/master/requirements.txt#L3), rq is constrained to `'>=0.6.0, <=0.12.0'`, so I guess the change should be ok if the constraint is updated to ==0.12.0.

What do you think @sduenas ?

**Comment by sduenas** [comment]
Merged. Thanks!

**Pull request merged**
